language: java
sudo: false
install: true

jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: code-not-found-spring-jms
    token:
      secure: $SONAR_TOKEN

env:
- PROJECT_DIR=spring-jms-activemq-hello-world
- PROJECT_DIR=spring-jms-annotations
- PROJECT_DIR=spring-jms-artemis-hello-world
- PROJECT_DIR=spring-jms-integration
- PROJECT_DIR=spring-jms-jmstemplate
- PROJECT_DIR=spring-jms-listener
- PROJECT_DIR=spring-jms-message-converter
- PROJECT_DIR=spring-jms-message-selector

script:
- cd $PROJECT_DIR
- mvn test -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

notifications:
  email: false
